# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10deab34fa9fca2ad066906a4ca2125afdf5d423946f15ce4917ce42041d5ac5836f4963a763939fd5c2a7ea1d6e6873a0a7eacd12cd8e2bf59d2a91a0069587

test:
  secret_key_base: a83d949cd880cf003949e9c88eda068b63df0d28cdbe03c8e16cf41dbdce89ee4c2c3ff2c04ef45a9b2f24effc64372be138b2fb43cf275d0ef599bde9ef6584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
