# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c2d4b54f2e3bbcc6352fceee5ec28ac124fff48e2e7465f0cbf689f72c24e3cd34376fbb1ba94000ccce0b5d1a6e2a780bb0e3935791ac512f424aeff26a934

test:
  secret_key_base: 0d4b8254f6ef2686e8b511fccfce03831d39fd70324acefd062ceb5b877c98b28e792ac11f087dc647793beac91eeb88f5f3e4c7fff9695b5f355d81b8a80485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
